---
ansible_user: ENC[AES256_GCM,data:OaDOIg==,iv:EyCU8Kjreh2zjQLCP3KgUCcmG8h9vatBWUr/J+3Zs3c=,tag:p1kA0F3Zl7eHMjsIRZ8wUg==,type:str]
ansible_host: ENC[AES256_GCM,data:roR7yhdjziNU//wO,iv:ItLcF9MzCHG2z3csByFUbXnxK8Kl4MotyH8DKeczuVY=,tag:4bmt09kgS+CkXRzEtdcwNA==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:rbBMADf7TWwwlDySDvVW5NOKI/v4rw==,iv:h23mp990ZbhnjiJc76Ug+YHdEuketiFRlReaH4n/yzA=,tag:CwCPg/Vv6vus+pkkHyMcGg==,type:str]
ansible_become_password: ENC[AES256_GCM,data:E8MpQwFwMIcN,iv:dfa/pYdtjjB++699KaXDryCgMn5ph3CRkV6k71GN0bc=,tag:cyD+iS0s1tWVrTsgLN9Vpw==,type:str]
sops:
  age:
    - recipient: age1dkl6vjdhx22jdwygztkcxkzyss0ajnzfp4k7ryljc0g6egqsuc0s9guqg7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTi91SXpaZDVzQzl2dDcx
        dW1lelU2U0hOYmFUUGRhdEd0cUFVOXQvT0dRCkVhbTZyQUxXRXhobUdJSzcvV20x
        dDBUaDhBYzJ1WkVmMk11OGhGRDFzQncKLS0tIGdEbWxYQloveUkyZFY1cWhMblBi
        YnJFdmJCaFF4SkVWc0hZLzRRaVpQbGMKVzbQs1Xh4HeffZHhfdbmvzj5enF5md3v
        pnDPG+J2V4qybwyaVtzYNNe7fYhqgmc3ncqoTAL3Flfz+gBJzwrJRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T17:50:05Z"
  mac: ENC[AES256_GCM,data:oMihqPj8LUqBCd4WbyjV+8CbmU7fLFV2ULjKqCbG9mNx+J04anIYm3n6AZP78UUK1wizsKbHGbi+Kmi2/vYaRb/pbQvXNIg6KkLdzN77Ux+EIP71KPqQ//fyx2H39ZZAcXP+UqrhdWega7nB2nWuXT8M9b7Vvwa8cbXYv9UOC+A=,iv:+bPGj9hGDxGuLoKuy6GmKpc0xFjPIcxGIP2wGrMS2Yo=,tag:O692cg3cqnO9I+3DVVKQtQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
