---
- name: Load shared variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/vars/terminal_packages.yml"
- name: Install Debian term debian specific packages
  become: true
  ansible.builtin.apt:
    name: "{{ debian_specific_packages }}"
    state: present
    update_cache: true
- name: Install Debian term common packages
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
