---
enabled_services:
  - traefik
  - adguard
  - ddns
  - certbot
  - wg-easy
  - crowdsec
  - portainer
  - gotify
  - glance
  - gatus
  - beszel
  ## Media
  - jellyfin
  - sonarr
  - radarr
  - prowlarr
  - bazarr
  - open-web-ui
  - qbittorrent
  - syncthing
